### ISSUE TITLE
[Bug]: adapter-satori的消息发送似乎不支持wsl的dev container开发环境？

### ISSUE THREAD

**Issue by Dz3yu** [nonebot/adapter-satori#35]
### 确认项

- [x] 问题的标题明确
- [x] 我翻阅过其他的 issue 并且找不到类似的问题
- [x] 我已经阅读了[相关文档](https://satori.js.org/zh-CN/) 并仍然认为这是一个 Bug
- [x] 我已经尝试过在最新的代码中修复这个问题

### 操作系统

Linux

### Python 版本

3.12.7

### NoneBot 版本

使用nb-cli 1.4.2创建

### 适配器

使用nb-cli 1.4.2创建

### 协议端

Chronocat

### 描述问题

本人使用的开发环境是wsl+dev container,使用指令“/test”测试消息发送,但是消息并没有正常发出。

### 复现步骤

宿主机测试chronocat正常，docker里面curl http://host.docker.internal:5500/也正常,重启设备未解决，更换使用宿主机 IP未解决。

使用代码
matcher = on_command("test")

@matcher.handle()
async def handle_receive(bot: Bot, event: MessageEvent):
    await bot.send(event, MessageSegment.text("Hello, world!"))
![Image](https://github.com/user-attachments/assets/fcb9f70f-069c-4ec6-852c-7e2293def0a2)

### 截图或日志

vscode ➜ /workspaces/PythonProject/test $ nb run
12-02 08:09:51 [SUCCESS] nonebot | NoneBot is initializing...
12-02 08:09:51 [INFO] nonebot | Current Env: dev
12-02 08:09:51 [DEBUG] nonebot | Loaded Config: {'driver': '~httpx+~websockets', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'satori_clients': [{'host': 'host.docker.internal', 'port': '5500', 'path': '', 'token': '89e6f2fc7d9ec8645a2eb7bb6a00c99b4e3e19c12f6e8dac902a511ebeb95dd2'}]}
12-02 08:09:51 [DEBUG] nonebot | Succeeded to load adapter "Satori"
12-02 08:09:51 [SUCCESS] nonebot | Succeeded to load plugin "test" from "src.plugins.test"
12-02 08:09:51 [SUCCESS] nonebot | Running NoneBot...
12-02 08:09:51 [DEBUG] nonebot | Loaded adapters: Satori
12-02 08:09:51 [INFO] nonebot | Application startup completed.
12-02 08:09:51 [DEBUG] nonebot | Satori | WebSocket Connection to ws://host.docker.internal:5500/v1/events established
12-02 08:09:51 [INFO] nonebot | Satori | Bot 2174827855 connected
12-02 08:09:56 [SUCCESS] nonebot | Satori 2174827855 | [message-created]: Message 7443723769382747347 from 曇天(3442731559)@[BOT测试群:186932654]: [Text(type='text', data={'text': '/test', 'styles': {}}, _children=[])]
12-02 08:09:56 [DEBUG] nonebot | Checking for matchers in priority 1...
12-02 08:09:56 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.test, lineno=7)
12-02 08:09:56 [DEBUG] nonebot | Running Matcher(type='message', module=src.plugins.test, lineno=7)
12-02 08:09:56 [DEBUG] nonebot | Running handler Dependent(call=handle_receive)
12-02 08:09:56 [DEBUG] nonebot | Satori | Bot 2174827855 calling API message_create
12-02 08:09:56 [INFO] nonebot | Matcher(type='message', module=src.plugins.test, lineno=7) running complete
12-02 08:09:56 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.test, lineno=7) failed.
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/adapters/satori/bot.py", line 235, in _request
    response = await self.adapter.request(request)
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/internal/adapter/adapter.py", line 92, in request
    return await self.driver.request(setup)
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/drivers/httpx.py", line 129, in request
    async with self.get_session(
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/internal/driver/abstract.py", line 269, in __aenter__
    await self.setup()
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/drivers/httpx.py", line 100, in setup
    self._client = httpx.AsyncClient(
TypeError: AsyncClient.__init__() got an unexpected keyword argument 'proxies'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/drivers/none.py", line 61, in run
    anyio.run(self._serve)
  File "/home/vscode/.local/lib/python3.12/site-packages/anyio/_core/_eventloop.py", line 74, in run
    return async_backend.run(func, args, {}, backend_options)
  File "/home/vscode/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2284, in run
    return runner.run(wrapper())
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1986, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/utils.py", line 254, in run_coro_with_shield
    return await coro
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/message.py", line 506, in check_and_run_matcher
    await _run_matcher(
> File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/internal/matcher/matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/internal/matcher/matcher.py", line 837, in simple_run
    await handler(
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/workspaces/PythonProject/test/src/plugins/test/__init__.py", line 11, in handle_receive
    await bot.send(event, MessageSegment.text("Hello, world!"))
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/adapters/satori/bot.py", line 261, in send
    return await self.send_message(event.channel.id, message)
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/adapters/satori/bot.py", line 275, in send_message
    return await self.message_create(channel_id=channel_id, content=str(message))
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/internal/adapter/bot.py", line 176, in call_api
    raise exception
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/internal/adapter/bot.py", line 128, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/adapters/satori/adapter.py", line 294, in _call_api
    return await api_handler(bot, **data)
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/adapters/satori/utils.py", line 39, in __call__
    return await self.func(inst, *args, **kwds)
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/adapters/satori/bot.py", line 320, in message_create
    res = await self._request(request)
  File "/home/vscode/.local/lib/python3.12/site-packages/nonebot/adapters/satori/bot.py", line 237, in _request
    raise NetworkError("API request failed") from e
nonebot.adapters.satori.exception.NetworkError: <NetWorkError message=API request failed>
12-02 08:09:56 [DEBUG] nonebot | Checking for matchers completed

> 

### Nonebot 配置项

```dotenv
ENVIRONMENT=dev
DRIVER=~httpx+~websockets

SATORI_CLIENTS='
[
  {
    "host": "host.docker.internal",
    "port": "5500",
    "path": "",
    "token": "89e6f2fc7d9ec8645a2eb7bb6a00c99b4e3e19c12f6e8dac902a511ebeb95dd2"
  }
]
'
```

**Comment by RF-Tar-Railt** [comment]
这个是httpx新版本的问题，你可以先降级httpx版本，然后等nonebot2更新

**Comment by Dz3yu** [comment]
回退到httpx 0.27.0，问题解决
